# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  jmx:
    enabled: true
  main:
    banner-mode: OFF
  lifecycle:
    timeout-per-shutdown-phase: 20s

  # ====================================================================================================================
  # = DATA SOURCE
  # ====================================================================================================================
  datasource:
    hikari:
      poolName: hikari-pool-dhwco

  # ====================================================================================================================
  # = JPA
  # ====================================================================================================================
  jpa:
    open-in-view: false
    properties:
      # https://docs.jboss.org/hibernate/orm/current/javadocs/org/hibernate/dialect/package-summary.html
      database-platform: org.hibernate.dialect.MariaDBDialect
      hbm2ddl:
        auto: validate
      # ================================================================================================================
      # = HIBERNATE
      # ================================================================================================================
      hibernate:
        jdbc:
          time_zone: Europe/Amsterdam

  # ====================================================================================================================
  # = WEB
  # ====================================================================================================================
  web:
    locale: nl

  # ====================================================================================================================
  # = THYMELEAF
  # ====================================================================================================================
  thymeleaf:
    prefix: classpath:/views

  # ====================================================================================================================
  # = JACKSON
  # ====================================================================================================================
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

# ======================================================================================================================
# = SERVER - INCLUDE AN ERROR MESSAGE JSON
# ======================================================================================================================
server:
  error:
    include-message: always

# ======================================================================================================================
# = OPENAPI - DISABLE BY DEFAULT
# ======================================================================================================================
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# ======================================================================================================================
# = LOGGING
# ======================================================================================================================
logging:
  pattern:
    console: '%date [%thread] %-5level %logger\(%mdc{IP}\) - [%mdc{RID}] %message%n'
  level:
    root: INFO
    com:
      github:
        computerhuis:
          dhwco: DEBUG
    org:
      springframework:
        security:
          web:
            csrf: DEBUG
