# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  # ====================================================================================================================
  # = MESSAGES
  # ====================================================================================================================
  messages:
    cache-duration: 1

  # ====================================================================================================================
  # = THYMELEAF
  # ====================================================================================================================
  thymeleaf:
    cache: false

# ======================================================================================================================
# = OPENAPI
# ======================================================================================================================
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# ======================================================================================================================
# = LOGGING
# ======================================================================================================================
logging:
  level:
    root: INFO
    com:
      github:
        computerhuis:
          dhwco: TRACE
